name: Nef_3_benchmark

on:
  push:
    branches: [ google-benchmark ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install -y libboost-dev libboost-thread-dev libgmp-dev libmpfr-dev libbenchmark-dev libbenchmark-tools
    - name: Install Python Dependencies
      run: sudo python -m pip install scipy
    - name: Checkout CGAL
      uses: actions/checkout@v2
      with:
        repository: CGAL/cgal
        path: cgal
    - name: Install CGAL
      run: |
        pushd cgal;
        mkdir build;
        pushd build;
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..;
        sudo make install;
        popd;
        popd;
    - name: Configure baseline
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Build baseline
      run: |
        make;
        mv ./benchmarks ./baseline;
        make clean;
    - name: Install CGAL contender
      run: |
        pushd cgal;
        git remote add giles https://github.com/GilesBathgate/cgal.git;
        git fetch giles;
        git checkout Nef_3-performance_k3_tree_vertices-GilesBathgate;
        pushd build;
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..;
        sudo make install;
        popd;
        popd;
    - name: Configure contender
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Build contender
      run: |
        make;
        mv ./benchmarks ./contender;
        make clean;
    - name: Test
      run: |
        timeout 30m /usr/share/benchmark/compare.py benchmarks ./baseline ./contender --benchmark_repetitions=10 | tee ./benchmark_results.txt;
        sed 's/\x1b\[[0-9;]*m//g' -i ./benchmark_results.txt;
    - name: Store results
      uses: actions/upload-artifact@v2
      with:
        name: benchmark_results
        path: ./benchmark_results.txt

